//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorProfile) DeepCopyInto(out *AcceleratorProfile) {
	*out = *in
	in.PerfParms.DeepCopyInto(&out.PerfParms)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorProfile.
func (in *AcceleratorProfile) DeepCopy() *AcceleratorProfile {
	if in == nil {
		return nil
	}
	out := new(AcceleratorProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActuationStatus) DeepCopyInto(out *ActuationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActuationStatus.
func (in *ActuationStatus) DeepCopy() *ActuationStatus {
	if in == nil {
		return nil
	}
	out := new(ActuationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Allocation) DeepCopyInto(out *Allocation) {
	*out = *in
	out.Load = in.Load
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Allocation.
func (in *Allocation) DeepCopy() *Allocation {
	if in == nil {
		return nil
	}
	out := new(Allocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadProfile) DeepCopyInto(out *LoadProfile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadProfile.
func (in *LoadProfile) DeepCopy() *LoadProfile {
	if in == nil {
		return nil
	}
	out := new(LoadProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProfile) DeepCopyInto(out *ModelProfile) {
	*out = *in
	if in.Accelerators != nil {
		in, out := &in.Accelerators, &out.Accelerators
		*out = make([]AcceleratorProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProfile.
func (in *ModelProfile) DeepCopy() *ModelProfile {
	if in == nil {
		return nil
	}
	out := new(ModelProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizedAlloc) DeepCopyInto(out *OptimizedAlloc) {
	*out = *in
	in.LastRunTime.DeepCopyInto(&out.LastRunTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizedAlloc.
func (in *OptimizedAlloc) DeepCopy() *OptimizedAlloc {
	if in == nil {
		return nil
	}
	out := new(OptimizedAlloc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerfParms) DeepCopyInto(out *PerfParms) {
	*out = *in
	if in.DecodeParms != nil {
		in, out := &in.DecodeParms, &out.DecodeParms
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PrefillParms != nil {
		in, out := &in.PrefillParms, &out.PrefillParms
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerfParms.
func (in *PerfParms) DeepCopy() *PerfParms {
	if in == nil {
		return nil
	}
	out := new(PerfParms)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunerPerfData) DeepCopyInto(out *TunerPerfData) {
	*out = *in
	in.UpdatedAt.DeepCopyInto(&out.UpdatedAt)
	in.PerfParms.DeepCopyInto(&out.PerfParms)
	if in.CovarianceMatrix != nil {
		in, out := &in.CovarianceMatrix, &out.CovarianceMatrix
		*out = make([][]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunerPerfData.
func (in *TunerPerfData) DeepCopy() *TunerPerfData {
	if in == nil {
		return nil
	}
	out := new(TunerPerfData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariantAutoscaling) DeepCopyInto(out *VariantAutoscaling) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariantAutoscaling.
func (in *VariantAutoscaling) DeepCopy() *VariantAutoscaling {
	if in == nil {
		return nil
	}
	out := new(VariantAutoscaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VariantAutoscaling) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariantAutoscalingList) DeepCopyInto(out *VariantAutoscalingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VariantAutoscaling, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariantAutoscalingList.
func (in *VariantAutoscalingList) DeepCopy() *VariantAutoscalingList {
	if in == nil {
		return nil
	}
	out := new(VariantAutoscalingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VariantAutoscalingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariantAutoscalingSpec) DeepCopyInto(out *VariantAutoscalingSpec) {
	*out = *in
	out.ScaleTargetRef = in.ScaleTargetRef
	in.ModelProfile.DeepCopyInto(&out.ModelProfile)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariantAutoscalingSpec.
func (in *VariantAutoscalingSpec) DeepCopy() *VariantAutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(VariantAutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariantAutoscalingStatus) DeepCopyInto(out *VariantAutoscalingStatus) {
	*out = *in
	out.CurrentAlloc = in.CurrentAlloc
	in.DesiredOptimizedAlloc.DeepCopyInto(&out.DesiredOptimizedAlloc)
	out.Actuation = in.Actuation
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TunerPerfData != nil {
		in, out := &in.TunerPerfData, &out.TunerPerfData
		*out = new(TunerPerfData)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariantAutoscalingStatus.
func (in *VariantAutoscalingStatus) DeepCopy() *VariantAutoscalingStatus {
	if in == nil {
		return nil
	}
	out := new(VariantAutoscalingStatus)
	in.DeepCopyInto(out)
	return out
}
